### ISSUE TITLE
Duplicates cause "An item with the same key has already been added." exception

### ISSUE THREAD

**Issue by nightroman** [editorconfig/editorconfig-core-net#15]
# Duplicates cause "An item with the same key has already been added." exception

#### Example:

```ini
root = true

[*.cs]
dotnet_sort_system_directives_first = true
dotnet_sort_system_directives_first = true
```

taken from:

- [.editorconfig#L88](https://github.com/ChilliCream/hotchocolate/blob/79f5cfdd60a5b731ae11b65c0381a42cfb90a8b7/.editorconfig#L88)
- [.editorconfig#L118](https://github.com/ChilliCream/hotchocolate/blob/79f5cfdd60a5b731ae11b65c0381a42cfb90a8b7/.editorconfig#L118)

#### Expected result:

`EditorConfigParser.GetConfigurationFilesTillRoot()` works without exceptions and probably keeps the last value if duplicates exist (as documented, if I am not mistaken).

#### Actual result:

`EditorConfigParser.GetConfigurationFilesTillRoot()` fails with "An item with the same key has already been added."

Exception details:

```
System.ArgumentException
  HResult=0x80070057
  Message=An item with the same key has already been added.
  Source=mscorlib
  StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at EditorConfig.Core.EditorConfigFile.Parse(String file)
   at EditorConfig.Core.EditorConfigFile..ctor(String file)
   at EditorConfig.Core.EditorConfigParser.<>c.<ParseConfigFilesTillRoot>b__16_0(String f)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at EditorConfig.Core.EditorConfigParser.<ParseConfigFilesTillRoot>d__16.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.<ReverseIterator>d__75`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Config.Invoke(IEditor editor, ModuleEditorEventArgs e) in ...
   at FarNet.Far0.InvokeModuleEditors(IEditor editor, Char* fileName)
```

**Comment by nightroman** [comment]
Just a guess, in [this line](https://github.com/editorconfig/editorconfig-core-net/blob/b24bad02782d35410d3a6d5cb7eefdd6b991cb73/src/EditorConfig.Core/EditorConfigFile.cs#L72) replace:

```
activeDict.Add(key, value);
```

with

```
activeDict[key] = value;
```

---

P.S. Is this repository and project maintained? No pressure, if it's not, it's not. But this is useful to know.
